# Numpy

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Array-creation" data-toc-modified-id="Array-creation-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Array creation</a></span><ul class="toc-item"><li><span><a href="#Zero-matrix" data-toc-modified-id="Zero-matrix-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Zero matrix</a></span></li></ul></li><li><span><a href="#Basic-operations" data-toc-modified-id="Basic-operations-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Basic operations</a></span></li><li><span><a href="#Slide-puzzle" data-toc-modified-id="Slide-puzzle-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Slide puzzle</a></span></li><li><span><a href="#Memory-puzzle" data-toc-modified-id="Memory-puzzle-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Memory puzzle</a></span></li><li><span><a href="#Mine-sweeper" data-toc-modified-id="Mine-sweeper-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Mine sweeper</a></span></li><li><span><a href="#2048" data-toc-modified-id="2048-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>2048</a></span></li></ul></div>

## Introduction

NumPy's main object is the **homogeneous multidimensional array**, that is an array where all elements are of the same type. This is different from the Python **list** type where elements can be of different types. 

    >>>a = [1, 1.23, True, 'abc']

The dimensions are called *axes*, the number of axes is called _rank_.

In [1]:
import numpy as np

A regular Python 2D list can be transformed into a NumPy array.

In [75]:
a0 = [[1, 2, 3], [4, 5, 6]]
a0

[[1, 2, 3], [4, 5, 6]]

This can become an **ndarray**

In [76]:
a = np.array(a0)
print(a)

[[1 2 3]
 [4 5 6]]


The type of this object is **numpy.ndarray**.

In [70]:
type(a)

numpy.ndarray

The **ndarray** is an object which has the following attributes:
* **ndim** - number of dimensions
* **shape** - the number of elements in each dimension
* **size** - the total number of elements

In [66]:
print(a.ndim, a.shape, a.size)

2 (2, 3) 6


The **ndarray** object has further attributes:
* **dtype** - the data type
* **itemsize** - the number of bytes occupied by the basic data element
* **data** - a pointer to the memory location where the data resides

In [77]:
print(a.dtype, a.itemsize, a.data)

int64 8 <memory at 0x105929480>


The ndarray can also be created with the **arange** function

In [82]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

This linear 1D ndarray can be changed in shape with **reshape()**

In [84]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
np.arange(15).reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Array creation

An **ndarray** can be created from a list or tuple. 

In [92]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [93]:
np.array((1.0, 2, 3))

array([1., 2., 3.])

If there is a mixture of int and float types, the ndarray will automatically be float.

In [103]:
np.array([1, 2, 3]).dtype

dtype('int64')

In [104]:
np.array([1., 2, 3]).dtype

dtype('float64')

With a keyword, the datatype can be specified, such as *complex*

In [105]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


### Zero matrix

A matrix with all elements being zero can easily be constructed

In [8]:
np.zeros((3,4), dtype=np.int8)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1, 4, 0.3)

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7])

In [13]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [15]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


## Basic operations
Arithmetic operations are done elementwise.

In [16]:
a = np.arange(10, 50, 10)
b = np.arange(4)

In [17]:
print(a-b, a+b, a*b)

[10 19 28 37] [10 21 32 43] [  0  20  60 120]


In [18]:
10*np.sin(b)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [19]:
c = np.random.random((2, 3))
print(c)
print(c.sum(), c.min(), c.max())

[[0.12853069 0.00435142 0.44023733]
 [0.0268558  0.68509113 0.33856548]]
1.6236318420570444 0.004351419202093254 0.685091132788756


In [20]:
c.sum()

1.6236318420570444

## Slide puzzle

Create a matrix for a slide puzzle.

In [21]:
n, m = 4, 4
grid = np.arange(n*m)
grid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
n, m = 4, 4
grid = np.arange(n*m)
np.random.shuffle(grid)
grid = grid.reshape(n, m)
print(grid)

[[ 4  2 13 11]
 [ 3  6 12  7]
 [ 8 14 10  1]
 [ 9  5  0 15]]


## Memory puzzle

Create a matrix for a memory puzzle.

In [23]:
n, m = 4, 6
grid = np.array(list(range(n*m//2))*2)
np.random.shuffle(grid)
grid = grid.reshape(n, m)
print(grid)

[[ 0  7 11  3 11  5]
 [10  8  0 10  5  4]
 [ 2  6  1  7  2  9]
 [ 9  1  3  4  6  8]]


## Mine sweeper

In [24]:
n, m = 5, 6
mines = 10
a = np.array([9]*mines + [0]*(n*m-mines))
np.random.shuffle(a)
a = a.reshape(n, m)
print(a)

[[9 9 9 0 9 9]
 [0 0 0 0 0 0]
 [0 0 0 0 0 9]
 [0 0 0 0 9 9]
 [9 0 0 0 9 0]]


In [25]:
b = np.zeros((n, m), dtype='int')
for i in range(n):
    for j in range(m):
        if a[i,j] != 9:
            b[i, j] = np.sum(a[max(0, i-1):min(i+2,n), max(0, j-1):min(j+2,m)])//9
print(b)

[[0 0 0 2 0 0]
 [2 3 2 2 3 3]
 [0 0 0 1 3 0]
 [1 1 0 2 0 0]
 [0 1 0 2 0 3]]


## 2048
Created by Gabriele Cirulli. Based on 1024 by Veewo Studio and conceptually similar to Threes by Asher Vollmer.
https://git.io/2048

Let's start with a 4x4 empty matrix.

In [26]:
grid = np.zeros((4,4), dtype=int)
print(grid)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Let's add a 2 somewhere.

In [27]:
grid[1,2]=2
grid

array([[0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Display the boolean matrix of the zeros.

In [28]:
grid == 0

array([[ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Find the positions of these zero locations.

In [29]:
a = np.transpose(np.nonzero(grid==0))
a

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [1, 0],
       [1, 1],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3]])

In [30]:
len(a)

15

In [31]:
b = np.random.randint(len(a))
b

14

In [32]:
pos = a[b]
pos

array([3, 3])

In [33]:
grid.ravel()[b]=2
grid

array([[0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0]])

Now let's put everything together in a function.

In [34]:
def add_element(grid):
    """Insert a 2 in one of the 0 fields. """
    z = np.transpose(np.nonzero(grid==0))
    index = np.random.randint(len(z))
    i, j = z[index]
    grid[i, j] = 2

There is another way of doing this, using the `np.flatnonzero` function.

In [35]:
c = np.flatnonzero(grid==0)
c

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 15])

In [36]:
d = np.random.choice(c, 1)
d

array([11])

In [37]:
grid.ravel()[d]=2
grid

array([[0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 2],
       [0, 0, 2, 0]])

Let's put togeter everything in a fonction.

In [38]:
def add_element2(grid):
    c = np.flatnonzero(grid==0)
    d = np.random.choice(c, 1)
    grid.ravel()[d]=2

Let's test the new fonction.

In [39]:
add_element2(grid)
grid

array([[0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 2],
       [2, 0, 2, 0]])

In [40]:
print(grid)

[[0 0 0 0]
 [0 0 2 0]
 [0 0 0 2]
 [2 0 2 0]]


Remove the zeros and shift right.

In [41]:
a = [2, 0, 8, 0]
a = [i for i in a if i==0]+[i for i in a if i!=0]
a

[0, 0, 2, 8]

Add two cells together, if they have the same contents.

In [42]:
def shift_line(a):
    # move the zeros to the left and the nonzero to the right
    a = [i for i in a if i==0]+[i for i in a if i!=0]
    # add two cells whith the same content
    if a[2]==a[3]:
        a = [0, a[0], a[1], a[2]*2]
    if a[1]==a[2]:
        a = [0, a[0], a[1]*2, a[3]]
    if a[0]==a[1]:
        a = [0, a[1]*2, a[2], a[3]]
    return a

In [43]:
shift_line([1,1,0,2])

[0, 0, 2, 2]

In [44]:
def shift_grid(grid):
    return np.array([shift_line(i) for i in grid])

In [45]:
add_element(grid)
grid = shift_grid(grid)
print(grid)

[[0 0 0 2]
 [0 0 0 2]
 [0 0 0 2]
 [0 0 0 4]]


In [46]:
grid

array([[0, 0, 0, 2],
       [0, 0, 0, 2],
       [0, 0, 0, 2],
       [0, 0, 0, 4]])

Turning a matrix in all 4 directions. The original is shifting to the RIGHT.

In [47]:
b = np.arange(16).reshape((4, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

`np.transpose` for shifting DOWN.

In [48]:
np.transpose(b)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

`np.fliplr` for shifting LEFT.

In [49]:
np.fliplr(b)

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

`np.fliplr(np.transpose(b))` for shifting UP.

In [50]:
np.fliplr(np.transpose(b))

array([[12,  8,  4,  0],
       [13,  9,  5,  1],
       [14, 10,  6,  2],
       [15, 11,  7,  3]])

In [51]:
def flip(grid, dir):
    if dir==1:
        grid = np.transpose(grid)
    elif dir==2:
        grid = np.fliplr(grid)
    elif dir==3:
        grid = np.transpose(np.fliplr(grid))
    return grid

In [52]:
b = np.arange(16).reshape((4, 4))
np.fliplr(np.transpose(flip(b, 3)))
flip(b, 3)

array([[ 3,  7, 11, 15],
       [ 2,  6, 10, 14],
       [ 1,  5,  9, 13],
       [ 0,  4,  8, 12]])

In [53]:
def shift_grid2(grid, dir):
    grid = flip(grid, dir)
    grid = np.array([shift_line(i) for i in grid], dtype=int)
    if dir==3:
        grid = np.fliplr(np.transpose(grid))
    else:
        grid = flip(grid, dir)
    return grid

In [54]:
b = np.zeros(16, dtype=int).reshape(4, 4)
add_element(b)
b

array([[0, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [55]:
b = shift_grid2(b, 2)
b

array([[0, 0, 0, 0],
       [2, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])