# Sudoku

Le jeu **Sudoku** est composé d'une grille de 9x9 cellules. 3x3 cellules sont groupé en box.

https://en.wikipedia.org/wiki/Sudoku_solving_algorithms

In [38]:
import numpy as np

In [31]:
s = """53  7    
6  195   
 98    6 
8   6   3
4  8 3  1
7   2   6
 6    28 
   419  5
    8  79
"""

In [32]:
len(s)

90

In [35]:
s1 = s.splitlines()
s1

['53  7    ',
 '6  195   ',
 ' 98    6 ',
 '8   6   3',
 '4  8 3  1',
 '7   2   6',
 ' 6    28 ',
 '   419  5',
 '    8  79']

In [156]:
a = [[1, 2, 3, 4, 5, 6, 7, 8, 9],
     [4, 5, 6, 7, 8, 9, 1, 2, 3],
     [7, 8, 9, 1, 2, 3, 4, 5, 6],
     [2, 3, 4, 5, 6, 7, 8, 9, 1],
     [5, 6, 7, 8, 9, 1, 2, 3, 4],
     [8, 9, 1, 2, 3, 4, 5, 6, 7],
     [3, 4, 5, 6, 7, 8, 9, 1, 2],
     [6, 7, 8, 9, 1, 2, 3, 4, 5],
     [9, 1, 2, 3, 4, 5, 6, 7, 8]]

In [22]:
set('123456789')

{'1', '2', '3', '4', '5', '6', '7', '8', '9'}

In [37]:
for line in s1:
    print(set(line)-{' '})

{'5', '7', '3'}
{'5', '9', '1', '6'}
{'9', '8', '6'}
{'8', '3', '6'}
{'4', '1', '3', '8'}
{'7', '2', '6'}
{'6', '2', '8'}
{'5', '9', '4', '1'}
{'7', '9', '8'}


In [30]:
s

'53  7    \n6  195   \n 98    6 \n8   6   3\n4  8 3  1\n7   2   6\n 6    28 \n   419  5\n    8  79\n'

We define the sudoko board as a numpy array.

In [161]:
a = np.array([  [5, 3, 0, 0, 7, 0, 0, 0, 0],
                [6, 0, 0, 1, 9, 5, 0, 0, 0],
                [0, 9, 8, 0, 0, 0, 0, 6, 0],
                [8, 0, 0, 0, 6, 0, 0, 0, 3],
                [4, 0, 0, 8, 0, 3, 0, 0, 1],
                [7, 0, 0, 0, 2, 0, 0, 0, 6],
                [0, 6, 0, 0, 0, 0, 2, 8, 0],
                [0, 0, 0, 4, 1, 9, 0, 0, 5],
                [0, 0, 0, 0, 8, 0, 0, 7, 9]])

We can print it to the console and the numbers are nicely aligned.

In [162]:
print(a)

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


We can check the number of cells

In [163]:
a.size

81

And also the shape. It's a 9x9 matrix.

In [164]:
a.ndim, a.shape

(2, (9, 9))

How many clues do we have ? Let's first flatten the matrix, and then remove the zeros.

## Access rows and columns

Accessing the first row

In [92]:
a[0,:]

array([5, 3, 0, 0, 7, 0, 0, 0, 0])

Accessing the first column

In [95]:
a[:,0]

array([5, 6, 0, 8, 4, 7, 0, 0, 0])

Elements of first column

In [98]:
d - set(a[:, 0]) - set(a[2, :])

{1, 2, 3}

Print the first 3 rows, and the set of numbers present.

In [106]:
for i in range(3):
    print(a[i,:], set(a[i,:])-{0})

[5 3 0 0 7 0 0 0 0] {3, 5, 7}
[6 0 0 1 9 5 0 0 0] {1, 5, 6, 9}
[0 9 8 0 0 0 0 6 0] {8, 9, 6}


Print the first 3 columns, and the set of numbers present.

In [107]:
for i in range(3):
    print(a[:, i], set(a[:, i])-{0})

[5 6 0 8 4 7 0 0 0] {4, 5, 6, 7, 8}
[3 0 9 0 0 0 6 0 0] {9, 3, 6}
[0 0 8 0 0 0 0 0 0] {8}


In [115]:
sq = a[0:3, 0:3]
sq

array([[5, 3, 0],
       [6, 0, 0],
       [0, 9, 8]])

In [117]:
set(sq.flatten())

{0, 3, 5, 6, 8, 9}

In [119]:
for i in range(3):
    sq = a[i*3:(i+1)*3, 0:3]
    print(sq)
    print(set(sq.flatten())-{0})
    print()

[[5 3 0]
 [6 0 0]
 [0 9 8]]
{3, 5, 6, 8, 9}

[[8 0 0]
 [4 0 0]
 [7 0 0]]
{8, 4, 7}

[[0 6 0]
 [0 0 0]
 [0 0 0]]
{6}



## Find the number of clues

In [66]:
a.flatten()

array([5, 3, 0, 0, 7, 0, 0, 0, 0, 6, 0, 0, 1, 9, 5, 0, 0, 0, 0, 9, 8, 0,
       0, 0, 0, 6, 0, 8, 0, 0, 0, 6, 0, 0, 0, 3, 4, 0, 0, 8, 0, 3, 0, 0,
       1, 7, 0, 0, 0, 2, 0, 0, 0, 6, 0, 6, 0, 0, 0, 0, 2, 8, 0, 0, 0, 0,
       4, 1, 9, 0, 0, 5, 0, 0, 0, 0, 8, 0, 0, 7, 9])

In [73]:
b = [i for i in a.flatten() if i>0]
print(b)

[5, 3, 7, 6, 1, 9, 5, 9, 8, 6, 8, 6, 3, 4, 8, 3, 1, 7, 2, 6, 6, 2, 8, 4, 1, 9, 5, 8, 7, 9]


In [74]:
len(b)

30

In [152]:
def clues(a):
    return len([i for i in a.flatten() if i>0])

In [165]:
clues(a)

30

Print for each row only the numbers used.

In [75]:
for row in a:
    print(set(row)-{0})

{3, 5, 7}
{1, 5, 6, 9}
{8, 9, 6}
{8, 3, 6}
{8, 1, 3, 4}
{2, 6, 7}
{8, 2, 6}
{1, 4, 5, 9}
{8, 9, 7}


In [82]:
d = set(range(1, 10))
d

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [83]:
for row in a:
    print(d - set(row))

{1, 2, 4, 6, 8, 9}
{2, 3, 4, 7, 8}
{1, 2, 3, 4, 5, 7}
{1, 2, 4, 5, 7, 9}
{2, 5, 6, 7, 9}
{1, 3, 4, 5, 8, 9}
{1, 3, 4, 5, 7, 9}
{2, 3, 6, 7, 8}
{1, 2, 3, 4, 5, 6}


In [86]:
b = a.transpose()
b

array([[5, 6, 0, 8, 4, 7, 0, 0, 0],
       [3, 0, 9, 0, 0, 0, 6, 0, 0],
       [0, 0, 8, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 8, 0, 0, 4, 0],
       [7, 9, 0, 6, 0, 2, 0, 1, 8],
       [0, 5, 0, 0, 3, 0, 0, 9, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 6, 0, 0, 0, 8, 0, 7],
       [0, 0, 0, 3, 1, 6, 0, 5, 9]])

In [89]:
for col in b:
    print(d - set(col))

{1, 2, 3, 9}
{1, 2, 4, 5, 7, 8}
{1, 2, 3, 4, 5, 6, 7, 9}
{2, 3, 5, 6, 7, 9}
{3, 4, 5}
{1, 2, 4, 6, 7, 8}
{1, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3, 4, 5, 9}
{8, 2, 4, 7}


Print only the sets of possible solutions.

In [179]:
def solve(a):
    for i in range(9):
        i0 = (i//3) * 3
        for j in range(9):
            j0 = (j//3) *3
            if a[i][j] == 0:
                sq = a[i0:i0+3, j0:j0+3]
                s = d - set(a[i, :]) - set(a[:, j]) - set(sq.flatten())
                print(i, ',' j, '=', s)
                if len(s)==1:
                    a[i, j] = list(s)[0]

SyntaxError: invalid syntax (<ipython-input-179-bf5cc2eb4482>, line 9)

In [166]:
solve(a)

{1, 2, 4}
{2, 6}
{8, 2, 4, 6}
{8, 1, 4, 9}
{1, 2, 4, 9}
{8, 2, 4}
{2, 4, 7}
{2, 4, 7}
{8, 3, 4, 7}
{2, 3, 4}
{8, 2, 4, 7}
{1, 2}
{2, 3}
{3, 4}
{2, 4}
{1, 3, 4, 5, 7}
{2, 4, 7}
{1, 2, 5}
{1, 2, 5, 9}
{9, 5, 7}
{1, 4, 7}
{9, 4, 5, 7}
{9, 2, 4, 5}
{2, 5}
{9, 2, 5, 6}
{5}
{9, 7}
{9, 2}
{1, 5}
{1, 3, 5, 9}
{9}
{1, 4}
{8, 4, 5}
{4, 5}
{1, 3, 9}
{1, 3, 4, 5, 7, 9}
{3, 5, 7}
{3}
{7}
{4}
{2, 3}
{8, 2, 7}
{2, 3, 7}
{3, 6}
{3}
{1, 2, 3}
{1, 2, 4, 5}
{1, 2, 3, 4, 5}
{2, 5, 6}
{2, 6}
{1, 6}


In [167]:
solve(a)

{1, 2, 4}
{2, 6}
{8, 2, 4, 6}
{8, 1, 4, 9}
{1, 2, 4, 9}
{8, 2}
{2, 4, 7}
{2, 4, 7}
{8, 3, 4, 7}
{2, 4}
{8, 2, 7}
{1, 2}
{2, 3}
{4}
{2}
{1, 3, 5, 7}
{7}
{1, 2, 5}
{1, 2, 5, 9}
{7}
{1, 4}
{9, 4, 5}
{9, 2, 4, 5}
{2}
{9, 6}
{9, 7}
{9}
{1, 5}
{1, 3, 5}
{1, 4}
{8, 4, 5}
{4, 5}
{1, 9}
{1, 5, 9}
{5}
{2}
{8, 7}
{7}
{6}
{1, 3}
{1, 4, 5}
{1, 3, 4, 5}
{2, 6}
{6}
{1}


In [168]:
solve(a)

{1, 2, 4}
{6}
{8}
{9, 4}
{1, 2, 4}
{2}
{4, 7}
{2, 4}
{8, 3, 4}
{4}
{8}
{1}
{3}
{5}
{1, 5}
{1, 5, 9}
{1, 4}
{4}
{2, 5}
{6}
{7}
{1, 5}
{1, 3, 5}
{1, 4}
{8}
{5}
{9}
{1}
{8}
{3}
{4, 5}
{4, 5}
{2}


In [169]:
solve(a)

{4}
{9}
{1}
{7}
{2}
{3}
{1, 5}
{9, 5}
{1}
{2}
{1}
{3}
{4}
{4, 5}
{5}


In [170]:
solve(a)

{5}
{9}
{4}


In [171]:
a

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [149]:
s2 = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 3, 0, 8, 5],
               [0, 0, 1, 0, 2, 0, 0, 0, 0],
               [0, 0, 0, 5, 0, 7, 0, 0, 0],
               [0, 0, 4, 0, 0, 0, 1, 0, 0],
               [0, 9, 0, 0, 0, 0, 0, 0, 0],
               [5, 0, 0, 0, 0, 0, 0, 7, 3],
               [0, 0, 2, 0, 1, 0, 0, 0, 0],
               [0, 0, 0, 0, 4, 0, 0, 0, 9]])     

In [155]:
clues(s2)

17

In [180]:
solve(s2)

0 0 {2, 3, 4, 6, 7, 8, 9}
0 1 {2, 3, 4, 5, 6, 7, 8}
0 2 {3, 5, 6, 7, 8, 9}
0 3 {1, 4, 6, 7, 8, 9}
0 4 {5, 6, 7, 8, 9}
0 5 {1, 4, 5, 6, 8, 9}
0 6 {2, 3, 4, 6, 7, 9}
0 7 {1, 2, 3, 4, 6, 9}
0 8 {1, 2, 4, 6, 7}
1 0 {2, 4, 6, 7, 9}
1 1 {2, 4, 6, 7}
1 2 {9, 6, 7}
1 3 {1, 4, 6, 7, 9}
1 4 {9, 6, 7}
1 6 {2, 4, 6, 7, 9}
2 0 {3, 4, 6, 7, 8, 9}
2 1 {3, 4, 5, 6, 7, 8}
2 3 {4, 6, 7, 8, 9}
2 5 {4, 5, 6, 8, 9}
2 6 {3, 4, 6, 7, 9}
2 7 {9, 3, 4, 6}
2 8 {4, 6, 7}
3 0 {1, 2, 3, 6, 8}
3 1 {1, 2, 3, 6, 8}
3 2 {8, 3, 6}
3 4 {8, 9, 3, 6}
3 6 {2, 3, 4, 6, 8, 9}
3 7 {2, 3, 4, 6, 9}
3 8 {8, 2, 4, 6}
4 0 {2, 3, 6, 7, 8}
4 1 {2, 3, 5, 6, 7, 8}
4 3 {2, 3, 6, 8, 9}
4 4 {8, 9, 3, 6}
4 5 {8, 9, 2, 6}
4 7 {2, 3, 5, 6, 9}
4 8 {8, 2, 6, 7}
5 0 {1, 2, 3, 6, 7, 8}
5 2 {3, 5, 6, 7, 8}
5 3 {1, 2, 3, 4, 6, 8}
5 4 {8, 3, 6}
5 5 {1, 2, 4, 6, 8}
5 6 {2, 3, 4, 5, 6, 7, 8}
5 7 {2, 3, 4, 5, 6}
5 8 {2, 4, 6, 7, 8}
6 1 {8, 1, 4, 6}
6 2 {8, 9, 6}
6 3 {8, 9, 2, 6}
6 4 {8, 9, 6}
6 5 {8, 9, 2, 6}
6 6 {8, 2, 4, 6}
7 0 {3, 4, 6, 7, 8, 9}
7

In [181]:
s2[1, 2] = 9
solve(s2)

0 0 {2, 3, 4, 6, 7, 8}
0 1 {2, 3, 4, 5, 6, 7, 8}
0 2 {3, 5, 6, 7, 8}
0 3 {1, 4, 6, 7, 8, 9}
0 4 {5, 6, 7, 8, 9}
0 5 {1, 4, 5, 6, 8, 9}
0 6 {2, 3, 4, 6, 7, 9}
0 7 {1, 2, 3, 4, 6, 9}
0 8 {1, 2, 4, 6, 7}
1 0 {2, 4, 6, 7}
1 1 {2, 4, 6, 7}
1 3 {1, 4, 6, 7}
1 4 {6, 7}
1 6 {2, 4, 6, 7}
2 0 {3, 4, 6, 7, 8}
2 1 {3, 4, 5, 6, 7, 8}
2 3 {4, 6, 7, 8, 9}
2 5 {4, 5, 6, 8, 9}
2 6 {3, 4, 6, 7, 9}
2 7 {9, 3, 4, 6}
2 8 {4, 6, 7}
3 0 {1, 2, 3, 6, 8}
3 1 {1, 2, 3, 6, 8}
3 2 {8, 3, 6}
3 4 {8, 9, 3, 6}
3 6 {2, 3, 4, 6, 8, 9}
3 7 {2, 3, 4, 6, 9}
3 8 {8, 2, 4, 6}
4 0 {2, 3, 6, 7, 8}
4 1 {2, 3, 5, 6, 7, 8}
4 3 {2, 3, 6, 8, 9}
4 4 {8, 9, 3, 6}
4 5 {8, 9, 2, 6}
4 7 {2, 3, 5, 6, 9}
4 8 {8, 2, 6, 7}
5 0 {1, 2, 3, 6, 7, 8}
5 2 {3, 5, 6, 7, 8}
5 3 {1, 2, 3, 4, 6, 8}
5 4 {8, 3, 6}
5 5 {1, 2, 4, 6, 8}
5 6 {2, 3, 4, 5, 6, 7, 8}
5 7 {2, 3, 4, 5, 6}
5 8 {2, 4, 6, 7, 8}
6 1 {8, 1, 4, 6}
6 2 {8, 6}
6 3 {8, 9, 2, 6}
6 4 {8, 9, 6}
6 5 {8, 9, 2, 6}
6 6 {8, 2, 4, 6}
7 0 {3, 4, 6, 7, 8, 9}
7 1 {3, 4, 6, 7, 8}
7 3 {3, 6, 7, 8, 9}

In [182]:
s2[6, 2] = 8
solve(s2)

0 0 {2, 3, 4, 6, 7, 8}
0 1 {2, 3, 4, 5, 6, 7, 8}
0 2 {3, 5, 6, 7}
0 3 {1, 4, 6, 7, 8, 9}
0 4 {5, 6, 7, 8, 9}
0 5 {1, 4, 5, 6, 8, 9}
0 6 {2, 3, 4, 6, 7, 9}
0 7 {1, 2, 3, 4, 6, 9}
0 8 {1, 2, 4, 6, 7}
1 0 {2, 4, 6, 7}
1 1 {2, 4, 6, 7}
1 3 {1, 4, 6, 7}
1 4 {6, 7}
1 6 {2, 4, 6, 7}
2 0 {3, 4, 6, 7, 8}
2 1 {3, 4, 5, 6, 7, 8}
2 3 {4, 6, 7, 8, 9}
2 5 {4, 5, 6, 8, 9}
2 6 {3, 4, 6, 7, 9}
2 7 {9, 3, 4, 6}
2 8 {4, 6, 7}
3 0 {1, 2, 3, 6, 8}
3 1 {1, 2, 3, 6, 8}
3 2 {3, 6}
3 4 {8, 9, 3, 6}
3 6 {2, 3, 4, 6, 8, 9}
3 7 {2, 3, 4, 6, 9}
3 8 {8, 2, 4, 6}
4 0 {2, 3, 6, 7, 8}
4 1 {2, 3, 5, 6, 7, 8}
4 3 {2, 3, 6, 8, 9}
4 4 {8, 9, 3, 6}
4 5 {8, 9, 2, 6}
4 7 {2, 3, 5, 6, 9}
4 8 {8, 2, 6, 7}
5 0 {1, 2, 3, 6, 7, 8}
5 2 {3, 5, 6, 7}
5 3 {1, 2, 3, 4, 6, 8}
5 4 {8, 3, 6}
5 5 {1, 2, 4, 6, 8}
5 6 {2, 3, 4, 5, 6, 7, 8}
5 7 {2, 3, 4, 5, 6}
5 8 {2, 4, 6, 7, 8}
6 1 {1, 4, 6}
6 3 {9, 2, 6}
6 4 {9, 6}
6 5 {9, 2, 6}
6 6 {2, 4, 6}
7 0 {3, 4, 6, 7, 9}
7 1 {3, 4, 6, 7}
7 3 {3, 6, 7, 8, 9}
7 5 {8, 9, 5, 6}
7 6 {8, 4, 5, 6}
7 7 {4

In [183]:
s2[1, 4] = 6
solve(s2)

0 0 {2, 3, 4, 6, 7, 8}
0 1 {2, 3, 4, 5, 6, 7, 8}
0 2 {3, 5, 6, 7}
0 3 {1, 4, 7, 8, 9}
0 4 {8, 9, 5, 7}
0 5 {1, 4, 5, 8, 9}
0 6 {2, 3, 4, 6, 7, 9}
0 7 {1, 2, 3, 4, 6, 9}
0 8 {1, 2, 4, 6, 7}
1 0 {2, 4, 7}
1 1 {2, 4, 7}
1 3 {1, 4, 7}
1 6 {2, 4, 7}
2 0 {3, 4, 6, 7, 8}
2 1 {3, 4, 5, 6, 7, 8}
2 3 {8, 9, 4, 7}
2 5 {8, 9, 4, 5}
2 6 {3, 4, 6, 7, 9}
2 7 {9, 3, 4, 6}
2 8 {4, 6, 7}
3 0 {1, 2, 3, 6, 8}
3 1 {1, 2, 3, 6, 8}
3 2 {3, 6}
3 4 {8, 9, 3}
3 6 {2, 3, 4, 6, 8, 9}
3 7 {2, 3, 4, 6, 9}
3 8 {8, 2, 4, 6}
4 0 {2, 3, 6, 7, 8}
4 1 {2, 3, 5, 6, 7, 8}
4 3 {2, 3, 6, 8, 9}
4 4 {8, 9, 3}
4 5 {8, 9, 2, 6}
4 7 {2, 3, 5, 6, 9}
4 8 {8, 2, 6, 7}
5 0 {1, 2, 3, 6, 7, 8}
5 2 {3, 5, 6, 7}
5 3 {1, 2, 3, 4, 6, 8}
5 4 {8, 3}
5 5 {1, 2, 4, 6, 8}
5 6 {2, 3, 4, 5, 6, 7, 8}
5 7 {2, 3, 4, 5, 6}
5 8 {2, 4, 6, 7, 8}
6 1 {1, 4, 6}
6 3 {9, 2, 6}
6 4 {9}
6 5 {2, 6}
6 6 {2, 4, 6}
7 0 {3, 4, 6, 7, 9}
7 1 {3, 4, 6, 7}
7 3 {8, 3, 6, 7}
7 5 {8, 5, 6}
7 6 {8, 4, 5, 6}
7 7 {4, 5, 6}
7 8 {8, 4, 6}
8 0 {1, 3, 6, 7}
8 1 {1, 3, 6, 7}
8 2

In [185]:
solve(s2)

0 0 {2, 3, 4, 6, 7, 8}
0 1 {2, 3, 4, 5, 6, 7, 8}
0 2 {3, 5, 6, 7}
0 3 {1, 4, 7, 8, 9}
0 4 {8, 5, 7}
0 5 {1, 4, 5, 8, 9}
0 6 {2, 3, 4, 6, 7, 9}
0 7 {1, 2, 3, 4, 6, 9}
0 8 {1, 2, 4, 6, 7}
1 0 {2, 4, 7}
1 1 {2, 4, 7}
1 3 {1, 4, 7}
1 6 {2, 4, 7}
2 0 {3, 4, 6, 7, 8}
2 1 {3, 4, 5, 6, 7, 8}
2 3 {8, 9, 4, 7}
2 5 {8, 9, 4, 5}
2 6 {3, 4, 6, 7, 9}
2 7 {9, 3, 4, 6}
2 8 {4, 6, 7}
3 0 {1, 2, 3, 6, 8}
3 1 {1, 2, 3, 6, 8}
3 2 {3, 6}
3 4 {8, 3}
3 6 {2, 3, 4, 6, 8, 9}
3 7 {2, 3, 4, 6, 9}
3 8 {8, 2, 4, 6}
4 0 {2, 3, 6, 7, 8}
4 1 {2, 3, 5, 6, 7, 8}
4 3 {2, 3, 6, 8, 9}
4 4 {8, 3}
4 5 {8, 9, 2, 6}
4 7 {2, 3, 5, 6, 9}
4 8 {8, 2, 6, 7}
5 0 {1, 2, 3, 6, 7, 8}
5 2 {3, 5, 6, 7}
5 3 {1, 2, 3, 4, 6, 8}
5 4 {8, 3}
5 5 {1, 2, 4, 6, 8}
5 6 {2, 3, 4, 5, 6, 7, 8}
5 7 {2, 3, 4, 5, 6}
5 8 {2, 4, 6, 7, 8}
6 1 {1, 4, 6}
6 3 {2, 6}
6 5 {2, 6}
6 6 {2, 4, 6}
7 0 {3, 4, 6, 7, 9}
7 1 {3, 4, 6, 7}
7 3 {8, 3, 6, 7}
7 5 {8, 5, 6}
7 6 {8, 4, 5, 6}
7 7 {4, 5, 6}
7 8 {8, 4, 6}
8 0 {1, 3, 6, 7}
8 1 {1, 3, 6, 7}
8 2 {3, 6, 7}
8 3 {2, 3

In [186]:
s2[3, 2] = 3
solve(s2)

0 0 {2, 3, 4, 6, 7, 8}
0 1 {2, 3, 4, 5, 6, 7, 8}
0 2 {5, 6, 7}
0 3 {1, 4, 7, 8, 9}
0 4 {8, 5, 7}
0 5 {1, 4, 5, 8, 9}
0 6 {2, 3, 4, 6, 7, 9}
0 7 {1, 2, 3, 4, 6, 9}
0 8 {1, 2, 4, 6, 7}
1 0 {2, 4, 7}
1 1 {2, 4, 7}
1 3 {1, 4, 7}
1 6 {2, 4, 7}
2 0 {3, 4, 6, 7, 8}
2 1 {3, 4, 5, 6, 7, 8}
2 3 {8, 9, 4, 7}
2 5 {8, 9, 4, 5}
2 6 {3, 4, 6, 7, 9}
2 7 {9, 3, 4, 6}
2 8 {4, 6, 7}
3 0 {8, 1, 2, 6}
3 1 {8, 1, 2, 6}
3 4 {8}
3 6 {9, 2, 4, 6}
3 7 {9, 2, 4, 6}
3 8 {2, 4, 6}
4 0 {8, 2, 6, 7}
4 1 {2, 5, 6, 7, 8}
4 3 {9, 2, 3, 6}
4 4 {3}
4 5 {9, 2, 6}
4 7 {9, 2, 5, 6}
4 8 {8, 2, 6, 7}
5 0 {1, 2, 6, 7, 8}
5 2 {5, 6, 7}
5 3 {1, 2, 4, 6}
5 4 set()
5 5 {1, 2, 4, 6}
5 6 {2, 3, 4, 5, 6, 7, 8}
5 7 {2, 3, 4, 5, 6}
5 8 {2, 4, 6, 7, 8}
6 1 {1, 4, 6}
6 3 {2, 6}
6 5 {2, 6}
6 6 {2, 4, 6}
7 0 {3, 4, 6, 7, 9}
7 1 {3, 4, 6, 7}
7 3 {8, 3, 6, 7}
7 5 {8, 5, 6}
7 6 {8, 4, 5, 6}
7 7 {4, 5, 6}
7 8 {8, 4, 6}
8 0 {1, 3, 6, 7}
8 1 {1, 3, 6, 7}
8 2 {6, 7}
8 3 {2, 3, 6, 7, 8}
8 5 {8, 2, 5, 6}
8 6 {8, 2, 5, 6}
8 7 {1, 2, 5, 6}


In [187]:
solve(s2)

0 0 {2, 3, 4, 6, 7, 8}
0 1 {2, 3, 4, 5, 6, 7, 8}
0 2 {5, 6, 7}
0 3 {1, 4, 7, 8, 9}
0 4 {5, 7}
0 5 {1, 4, 5, 8, 9}
0 6 {2, 3, 4, 6, 7, 9}
0 7 {1, 2, 3, 4, 6, 9}
0 8 {1, 2, 4, 6, 7}
1 0 {2, 4, 7}
1 1 {2, 4, 7}
1 3 {1, 4, 7}
1 6 {2, 4, 7}
2 0 {3, 4, 6, 7, 8}
2 1 {3, 4, 5, 6, 7, 8}
2 3 {8, 9, 4, 7}
2 5 {8, 9, 4, 5}
2 6 {3, 4, 6, 7, 9}
2 7 {9, 3, 4, 6}
2 8 {4, 6, 7}
3 0 {1, 2, 6}
3 1 {1, 2, 6}
3 6 {9, 2, 4, 6}
3 7 {9, 2, 4, 6}
3 8 {2, 4, 6}
4 0 {8, 2, 6, 7}
4 1 {2, 5, 6, 7, 8}
4 3 {9, 2, 6}
4 5 {9, 2, 6}
4 7 {9, 2, 5, 6}
4 8 {8, 2, 6, 7}
5 0 {1, 2, 6, 7, 8}
5 2 {5, 6, 7}
5 3 {1, 2, 4, 6}
5 4 set()
5 5 {1, 2, 4, 6}
5 6 {2, 3, 4, 5, 6, 7, 8}
5 7 {2, 3, 4, 5, 6}
5 8 {2, 4, 6, 7, 8}
6 1 {1, 4, 6}
6 3 {2, 6}
6 5 {2, 6}
6 6 {2, 4, 6}
7 0 {3, 4, 6, 7, 9}
7 1 {3, 4, 6, 7}
7 3 {8, 3, 6, 7}
7 5 {8, 5, 6}
7 6 {8, 4, 5, 6}
7 7 {4, 5, 6}
7 8 {8, 4, 6}
8 0 {1, 3, 6, 7}
8 1 {1, 3, 6, 7}
8 2 {6, 7}
8 3 {2, 3, 6, 7, 8}
8 5 {8, 2, 5, 6}
8 6 {8, 2, 5, 6}
8 7 {1, 2, 5, 6}
